---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates Amazon(CentOS)
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Amazon"

  - name: install updates (Ubuntu)
    apt:
      upgrade: yes
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php packages for Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php packages for Amazon(CentOS)
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Amazon"

- hosts: db_servers
  become: true
  tasks:

  - name: Install MariaDB package Amazon(CentOS)
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "Amazon"

  - name: Install MariaDB package on Ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:
  
  - name: install samba package
    package: 
      name: samba
      state: latest
