---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates Amazon(CentOS)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Amazon"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: yes
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:
  
  - name: create simone user
    tags: always
    user:
      name: simone
      groups: root

#  - name: add ssh key for simone
#    tags: always
#    authorized_key: #modul specifican za ovaj play
#      user: simone
#      key: ""
#  - name: add sudoers file for simone
#    tags: always
#    copy:
#      src: sudoer_simone
#      dest: /etc/sudoers.d/simone
#      owner: root
#      group: root
#      mode: 0440

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

#remote_src: yes znaci da fajl koji treba biti unzipovan dolazi sa remote server# da ansible ne bi trazio po fajlovima zna da se radi o remote, mozda je izbacen# u play-u iznad instaliramo unzip paket i onda play ispod koristi modul/paket  # unarchive koji je od unzip da bi otpakovao

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_amd64.zip 
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root


- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php packages for Ubuntu
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php packages for Amazon(CentOS)
    tags: apache,httpd,centos 
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Amazon"

  - name: start httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "Amazon"

  - name: change e-mail address for admin
    tags: apache,centos,httpd
    lineinfile: #kada radis sa conf fajlovima i change lines, pokreni dva puta playbook
#kako bi bio siguran da drugi put nema nikakvih promena, jer kada imas typo u tim fajlovima#imaces problem jer ce on tu liniju dodavati iznova svaki put i nece raditi kako treba
      path: /etc/httpd/conf/httpd.conf #lokacija fajla u kom se menja linija
      regexp: '^ServerAdmin' #linija koja treba biti izmenjena, npr ova pocinje ovako
      line: ServerAdmin somebody@somewhere.net #sta se upisuje na toj liniji
    when: ansible_distribution == "Amazon"
    register: httpd #znaci ako ova linija ukljuci state changed trigerovace se play ispod

  - name: restart httpd Amazon(centos)
    tags: apache,centos,httpd
    service: #npr httpd je servis i onda koristimo ovo i radimo izmene kao ovde npr state
      name: httpd
      state: restarted
    when: httpd.changed #znaci da ce se ovaj play pozvati samo kad je httpd changed

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: Install MariaDB package Amazon(CentOS)
    tags: centos,db,mariadb
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "Amazon"

  - name: Install MariaDB package on Ubuntu
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:
  
  - name: install samba package
    tags: samba
    package: 
      name: samba
      state: latest
