- name: install apache and php packages
  tags: apache,apache2,ubuntu
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: start and enable apache service
  tags: apache,centos,httpd
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: change e-mail address for admin
  tags: apache,centos,httpd
  lineinfile: #kada radis sa conf fajlovima i change lines, pokreni dva puta playbook
#kako bi bio siguran da drugi put nema nikakvih promena, jer kada imas typo u tim fajlovima#imaces problem jer ce on tu liniju dodavati iznova svaki put i nece raditi kako treba
    path: /etc/httpd/conf/httpd.conf #lokacija fajla u kom se menja linija
    regexp: '^ServerAdmin' #linija koja treba biti izmenjena, npr ova pocinje ovako
    line: ServerAdmin somebody@somewhere.com #sta se upisuje na toj liniji
  when: ansible_distribution == "Amazon"
  notify: restart_apache #kada se desi npr ova promena, trigerovace task po imenu restart_a#pache( u nasem slucaju on je u handlers )

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
